name = "PRIMA"
uuid = "0a7d04aa-8ac2-47b3-b7a7-9dbd6ad661ed"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "0.1.1"

[deps]
PRIMA_jll = "eead6e0c-2d5b-5641-a95c-b722de96d551"
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
PRIMA_jll = "0.7.1"
TypeUtils = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
